package com.vanessa.librarymanagementapi.book.model;

public enum BookGenre {
    HISTORICAL_FICTION, ADVENTURE, SCIENCE_FICTION, HORROR, DYSTOPIAN, MEMOIR, SELF_HELP, CLASSIC, YOUNG_ADULT, CHILDREN, CRIME, CONTEMPORARY, PARANORMAL, HUMOR, DRAMA, SHORT_STORY, WAR, WESTERN, FAIRY_TALE, PHILOSOPHY
}
